In [15]:
import pandas as pd
import numpy as np
from time import time
import copy
import datetime
from sklearn import linear_model
from sklearn.cross_validation import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn import metrics
from imblearn.under_sampling import RandomUnderSampler
from imblearn.under_sampling import NeighbourhoodCleaningRule
from multiprocessing import Process
import MySQLdb
import json

In [27]:
connection = MySQLdb.connect(host='localhost', port=3306, user='root', passwd='admin', db='edxapp', charset='utf8')
sm = pd.read_sql("select student_id as user_id, module_id, grade, created from courseware_studentmodule where course_id = 'KNU/101/2014_T2'" + \
                   " and module_type = 'problem'",con=connection).fillna(0)
certificates = pd.read_sql("select user_id, 1 as status from certificates_generatedcertificate where course_id = 'KNU/101/2014_T2'" + \
                   " and status = 'downloadable'", index_col='user_id', con=connection)

In [28]:
st = time()
modules = sm.module_id.unique().tolist()
result = []
for module in modules:
    first = sm[sm.module_id == module].created.min()
    result.append({'name':module,'date':first})
labels = map(lambda x: x['name'],sorted(result,key=lambda x: x['date']))
rebased = sm.pivot(index='user_id',columns='module_id',values='grade')
rebased = rebased[labels]
print time()-st

0.074000120163

In [32]:
pd.merge(rebased, certificates, how='left', left_index=True, right_index=True).fillna(0)

module_id,i4x://KNU/101/problem/e39129c796754099b0974db74c5b5b01,i4x://KNU/101/problem/43dbbb5417294a0faa1c43f02473e7ec,i4x://KNU/101/problem/84d4314a7fd041f59e9219de9b4e7cd0,i4x://KNU/101/problem/7ac56261c85548fd97ae8a56e5a355f6,i4x://KNU/101/problem/b9daef58e5884fa8b0c36c5c9bd233ce,i4x://KNU/101/problem/7fb5b2515e09416f9977f465f909a746,i4x://KNU/101/problem/e663ed76dc9445dead9354a158daf163,i4x://KNU/101/problem/f1fb3e3d588a4380b7226b87029c284c,status
user_id,,,,,,,,,
8,10,10,9,5,0,10,20,0,1
9,0,0,0,0,0,0,2,0,0
13,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0
26,8,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0
63,7,0,0,0,0,0,0,0,0
90,0,0,0,0,0,0,0,0,0
115,0,0,0,0,0,0,0,0,0
117,9,0,0,3,0,0,0,0,0
133,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0
144,0,0,0,0,0,0,0,0,0
152,0,0,0,0,0,0,0,0,0
160,9,9,0,0,0,0,0,0,0
161,10,9,10,5,8,10,20,0,1
164,0,0,0,0,0,0,0,0,0
168,0,0,0,0,0,0,0,0,0
175,8,9,9,3,8,5,15,0,1
180,0,0,0,0,0,0,0,0,0
185,10,9,10,5,9,9,20,0,1
193,10,9,8,3,9,9,20,0,1
198,10,10,0,0,0,0,0,0,0
203,8,7,8,4,7,6,15,0,1
206,0,0,0,0,0,0,0,0,0
209,5,7,9,0,0,0,0,0,0
212,10,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
122793,0,0,0,0,0,0,0,0,0
122806,10,0,0,0,0,0,0,0,0
122836,0,0,0,0,0,0,0,0,0
122929,0,0,0,0,0,0,0,0,0
122930,0,0,0,0,0,0,0,0,0
122932,0,0,0,0,0,0,0,0,0
122972,0,0,0,0,0,0,0,0,0
123039,9,9,9,0,0,0,0,0,0
123059,5,9,10,4,0,0,0,0,0
123238,0,0,0,0,0,0,0,0,0
123263,0,0,0,0,0,0,0,0,0
123314,8,8,0,0,0,0,0,0,0
123347,0,0,0,0,0,0,0,0,0
123498,0,0,0,0,0,0,0,0,0
123546,4,10,6,0,0,0,0,0,0
123587,7,0,0,0,0,0,0,0,0
123594,0,0,0,0,0,0,0,0,0
123604,0,0,0,0,0,0,0,0,0
123782,10,0,0,0,0,0,0,0,0
123920,0,0,0,0,0,0,0,0,0
123992,0,0,0,0,0,0,0,0,0
124084,10,0,0,0,0,0,0,0,0
124184,0,0,0,0,0,0,0,0,0
124248,0,0,0,0,0,0,0,0,0
124291,5,0,0,0,0,0,0,0,0
124308,0,0,0,0,0,0,0,0,0
124429,9,0,0,0,0,0,0,0,0
124506,9,0,0,0,0,0,0,0,0
124578,6,0,0,0,0,0,0,0,0
124659,7,4,6,4,8,6,17,0,0